### ISSUE TITLE
Document opening in read only mode

### ISSUE THREAD

**Issue by Nikesh-Newaskar** [OpenMarshal/npm-WebDAV-Server#10]
Hi,

I am trying to test the document editing scenario where I am trying to open a document from word with a valid link to the webdav server. So when word tries to open the docx file it first pops up a log-in pop up and then after giving the creds it opens up the document but in read-only mode. I was expecting it to open  up so that when I edit something and save it, it should save the changes made in target location.

For e.g. I was trying to open this path from word - http://localhost:1377/Shared/Summary.docx
Here is the node.js code for the webdav-server -
```javascript
'use strict';
const webdav = require('webdav-server').v2;

 var  davServer = new webdav.WebDAVServer({    
        port: 1337
    });

 var fileMap = new webdav.PhysicalFileSystem('C:\\FileShare');
 davServer.setFileSystem('/Shared', fileMap, (success) => console.log('File shared mapped'));
 davServer.start(() => console.log('WebDAV Server READY...'));
```

Can you please help me figure out as to why the file is opening in read-only mode?. I am expecting it to work as a webDAV server on IIS where you can directly open and edit the documents.

**Comment by AdrienCastex** [comment]
Hello,

I tried to open a `docx` file with your code and it is working.

It just open in read-only first, then it displays a message saying that the file has been opened from a potentially dangerous place (because it's from the network), but you have the possibility to open it with the button `Activate the modifications` (or something like that) and it turns Word into read/write mode. If you don't see this message or the button, maybe it's a problem from your settings in Word, but not a problem from the WebDAV server or from your code (it is correct).

I hope that helped you.

**Comment by Nikesh-Newaskar** [comment]
Hello,

I tried to see if there are any settings in Word that could cause this behavior but all the settings are correct.
I added one txt file at that location and tried to open it in notepad with similar link http://localhost:1377/Shared/test.txt

It opened the file in notepad and I was able to edit the file and save it which updated the file at source location. So I am not sure what is the problem with the MS Office.

**Comment by AdrienCastex** [comment]
I believe that if you start the server with HTTPS or use a SSL Gateway, this restriction will not occur.
Your security settings must be very strict if you are not able to switch to the edit mode.

Two choices :
* Use SSL
* Lower your security settings

**Comment by Nikesh-Newaskar** [comment]
Are there examples on configuring the server with HTTPS and SSL connfiguration.?

**Comment by AdrienCastex** [comment]
You can find information in the wiki page about [server's options (`https` option)](https://github.com/OpenMarshal/npm-WebDAV-Server/wiki/Server's-options-and-customizations-%5Bv2%5D) and find information/examples from the [Node.js documentation](https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener).

So it would be something like :
```javascript
const httpsOptions = {
    key: fs.readFileSync('test/fixtures/keys/agent2-key.pem'),
    cert: fs.readFileSync('test/fixtures/keys/agent2-cert.pem')
};

var davServer = new webdav.WebDAVServer({    
    port: 1337,
    https: httpsOptions
});
```

You might find more [here about the creation of these `.pem` files](https://docs.nodejitsu.com/articles/HTTP/servers/how-to-create-a-HTTPS-server/).

**Comment by Nikesh-Newaskar** [comment]
Hi,

Thanks for the information. I tried setting up HTTPS option and open the document in word but now when trying to open the document word says "Sorry, we couldn't open '<#link of document>'

I tried to use this same link in browser and it was able to download the file.

**Comment by AdrienCastex** [comment]
With an unregistered certificate, you must have a warning saying that the certificate might be invalid (this is the message I get when I do it over SSL).

With strict security settings, Word can just refuse to open the document (which seems to be your case).

Two choices :
* Register the certificate
* Use a SSL gateway
* Ask your administrator to give some freedom

I don't think I can help you more.
