### ISSUE TITLE
[Bug] Range requests return invalid results

### ISSUE THREAD

**Issue by perry-mitchell** [OpenMarshal/npm-WebDAV-Server#12]
When making a range request to my personal ownCloud (WebDAV) server, I get correct results. For instance, if I request the file "/img.png" with the following headers:

```javascript
{
    Authorization: 'Basic (creds)',
    Range: 'bytes=0-499'
}
```

I should get a result with a length of 500 bytes as specified in the [HTTP 1.1 spec](https://tools.ietf.org/html/rfc7233#section-2.1). The range `0-499` is inclusive:

> the byte positions specified are inclusive

When hosting a file with this server, and sending the same headers, I get the following response headers:

```javascript
{
    dav: ['1,2'],
    server: ['webdav-server/1.8.0'],
    'www-authenticate': ['Basic realm="realm"'],
    allow: ['PROPPATCH,PROPFIND,OPTIONS,DELETE,UNLOCK,COPY,LOCK,MOVE,HEAD,POST,PUT,GET'],
    'accept-ranges': ['bytes'],
    'content-type': ['image/png'],
    'content-length': ['499'],
    'content-range': ['bytes 0-499/*'],
    date: ['Tue, 01 Aug 2017 18:21:23 GMT'],
    connection: ['close']
}
```

The length of `499` here is incorrect. It seems to miss the last index perhaps?

EDIT: The issue could possibly be with [this line](https://github.com/OpenMarshal/npm-WebDAV-Server/blob/abf6b3493eebb51bed557a4450ca75c39c5dfe54/src/server/v2/commands/Get.ts#L39) as slice doesn't include the last index.. What are your thoughts?

**Comment by AdrienCastex** [comment]
Hello,

You are right, it was not working.
I fixed the problem (some times a little `+1` was missing and some length calculations were wrong). There were no tests in the test set to check if the `Range` was working. I added them too.

You can find the fix in the version `2.1.0`.
Note that the `Range` header is not completely implemented yet (no `bytes=0-499,-1,50-`, only `bytes=...-...`).

I let you close the issue if you think that the problem is solved.
Thank you very much for your contribution.

**Comment by perry-mitchell** [comment]
Thanks for the extremely quick response @AdrienCastex! If you don't mind I'll test this in a couple of hours and will close when confirmed, thanks.

> Note that the Range header is not completely implemented yet (no bytes=0-499,-1,50-, only bytes=...-...).

Does this mean that `bytes=-50` and `bytes=512-` won't work? Or did you just mean multiple range sequences?

**Comment by AdrienCastex** [comment]
I meant sequences, `bytes=-50` and `bytes=512-` are not supported yet.

**Comment by perry-mitchell** [comment]
Thanks for the clarification. I might attempt a PR later.

**Comment by perry-mitchell** [comment]
Worked a treat, thanks! I'll make a PR for the optional end parameter.
