### ISSUE TITLE
How to use this package

### ISSUE THREAD

**Issue by Daxcor69** [OpenMarshal/npm-WebDAV-Server#133]
I am sorry, I am just not understanding the docs.  I am first trying to just get a simple server running and connecting via cyberduck - webdav client.  I am running this locally on my windows computer.  When I try to connect to the running instance on localhost:9900 I get the following output on the console.

```
>> HEAD / > 405 Method Not Allowed
undefined
>> HEAD / > 405 Method Not Allowed
undefined
```
 I am using the supplied example

```
const server = new webdav.WebDAVServer({
  port: 9900,
});

server.afterRequest((arg, next) => {
  // Display the method, the URI, the returned status code and the returned message
  console.log(">>", arg.request.method, arg.requested.uri, ">", arg.response.statusCode, arg.response.statusMessage);
  // If available, display the body of the response
  console.log(arg.responseBody);
  next();
});

server.start(() => console.log("READY"));
```

I have tried on different ports, I went with 9900 to get above the privileged ports.  Here is the cyberduck setup

![image](https://github.com/OpenMarshal/npm-WebDAV-Server/assets/61804230/fbac578e-f192-4b3b-8c8a-fbe13a6547a1)

I am sorry if I am missing something simple.

Brad

**Comment by Daxcor69** [comment]
I am wondering if this is due to the fact I am trying to connect via http and NOT https.  I would be running this behind a proxy, so the connection would be http from the proxy. Is this possible?

**Comment by AdrienCastex** [comment]
This is just a test code. If you want to go further, like receiving usable data from the server, you must add more configuration (mount a file system). Here is an example from the wiki:

```typescript
server.rootFileSystem().addSubTree(server.createExternalContext(), {
    'folder1': {                                // /folder1
        'file1.txt': webdav.ResourceType.File,  // /folder1/file1.txt
        'file2.txt': webdav.ResourceType.File   // /folder1/file2.txt
    },
    'file0.txt': webdav.ResourceType.File       // /file0.txt
})
```

**Comment by Daxcor69** [comment]
ok fair enough, however, we  are not even getting past authentication, I have requireAuthentification: false,  and I am still not even getting past the login stage.

**Comment by Daxcor69** [comment]
Here is a bare bones server that authenticates wit Basic Auth, and username and password as 'username' and 'password'. This will get you started.

```
const webdav = require("webdav-server").v2;

const userManager = new webdav.SimpleUserManager();
const user = userManager.addUser("username", "password", false);

// Create a new server instance
const server = new webdav.WebDAVServer({
  // HTTP Basic authentication
  httpAuthentication: new webdav.HTTPBasicAuthentication(userManager, "Default realm"),
  rootFileSystem: new webdav.PhysicalFileSystem("/tmp/"),

});

server.start((s) => console.log("Ready on port", s.address().port));
```
