### ISSUE TITLE
[Feature] User quota

### ISSUE THREAD

**Issue by perry-mitchell** [OpenMarshal/npm-WebDAV-Server#15]
Hi,

I was wondering if quota management was planned as a potential feature for this project? The properties that would be useful here would be:

 * [quota-available-bytes](https://tools.ietf.org/html/rfc4331#section-3)
 * [quota-used-bytes](https://tools.ietf.org/html/rfc4331#section-4)

I understand this isn't part of the same RFC, but is a commonplace feature among many webdav services.

**Comment by AdrienCastex** [comment]
Hello,

It was not planned.

This project is made to be highly modular, to allow to mount file systems which manage, for instance, resources from remote servers (so maybe no access to the remote hardware information) or virtual resources.

But, it is possible to implement these properties by implementing a custom file system (inheriting from another file system, if you want).

For my part, I will try to see if I can make a standard implementation or wrapper to help to implement that. I will create an example to guide you to the best way to implement these properties and the limitation system.

Are you in a hurry about these properties?

**Comment by perry-mitchell** [comment]
> implementing a custom file system

Well I'd preferably not want to implement additional webdav features myself - that's the responsibility of the server imo. Obviously if it's not on the roadmap for your project then so be it, but for instance many other webdav servers implement the standard. If you're not planning to then we could close this of course 🙂

> Are you in a hurry about these properties?

Definitely not in the hurry for these ones.. but I might use jsDAV for the quota side of things and this project for everything else as I'm currently just using these servers as a comprehensive testing rig. So definitely not important to go changing or adding things for me 😅

**Comment by AdrienCastex** [comment]
Hello,

I believe that you implemented these tests with `jsDAV` and might not want to change your implementation now, but for those who will find the issue : there is now a feature to manage the storage capacity (leading to the addition of the `quota-available-bytes` and `quota-used-bytes` tags).

```javascript
const server = new webdav.WebDAVServer({
    storageManager: new webdav.PerUserStorageManager(100) // 100 is the limit of bytes storable (including the name/path, the properties and the content)
});
```

I let you close the issue if you don't want to check if it does the trick (and let someone else reopen the issue if a problem is encountered) or if you think it is working as expected.

Thank you for your contribution.

**Comment by perry-mitchell** [comment]
Hi!

That's really great news. I actually have not resorted to using jsdav (I'd like to avoid using it altogether), and have instead just mocked the response for now. 

I'll definitely give this a test shortly - thanks for the quick implementation.

**Comment by AdrienCastex** [comment]
Hello,

Have you been able to test the implementation of `quotas`?

**Comment by perry-mitchell** [comment]
Unfortunately no, I've been quite busy since I started this issue. I've been testing using [mocked responses](https://github.com/perry-mitchell/webdav-client/blob/master/test/specs/getQuota.spec.js) since and haven't had a chance to test with the latest version of your library.
