### ISSUE TITLE
Use existing http server

### ISSUE THREAD

**Issue by ThauEx** [OpenMarshal/npm-WebDAV-Server#17]
Hi,
can I somehow use an existing http server from node js? I want to have the webdav inside a subfolder and on `/` should be a normal website. Can this be done somehow?

**Comment by AdrienCastex** [comment]
Hello,

The server is meant to be a standalone server.

But, if you are using `Express` (for instance), you can use the server's methods to retrieve the requested resource in the server. The server doesn't need to be running to work, but the auto-save feature will not start (version 2.2.3), but you will be able to call the `server.autoSave()` method in the next version (2.3.0).

Another option is to implement a website file system and mount it as root, then mount a virtual file system (or whatever file system you need) on a sub-folder.

I hope that helped you.

**Comment by ThauEx** [comment]
I will have a look, thank you.
