### ISSUE TITLE
PROPFIND fails when a dead link is in the directory

### ISSUE THREAD

**Issue by ChristophAtAdlos** [OpenMarshal/npm-WebDAV-Server#20]
There is a bug with PROPFIND in case of orphaned symlinks:  

**How to reproduce:**
* Create a file or directory in a path (e.g. /webdav/appdata/myFile.txt)
* Create a symlink to the just created path (e.g. /webdav/appdata/linkToMyFile.txt -> /webdav/appdata/myFile.txt)
* (re)move the before created file (myFile.txt) and let the orphaned symlink as it is
* Make a PROPFIND call to the parent directory.

**Expected behavior:**
Propfind returns all available information concerning the given path.

**Actual behavior:**
`PROPFIND http://127.0.0.1:8080/webdav/appdata/ 404 (Not Found)`

If this would be on the orphaned symlink itself, I could understand this, but it's the parent directory.

Versions:
webdav-server: 2.3.3
node: LTS 6.11.3
os. openSUSE 42.1 64bit  and also Windows 10 Pro 64bit (only with symlinks, hardlinks are not concerned)

**Comment by AdrienCastex** [comment]
Hello,

You are right.
Until now, if there is an error in the child resources while performing a `PROPFIND` with a depth greater than `0`, the error will be the result of the request.

I modified (v2.3.4) this behaviour to be more WebDAV compliant and to provide the error in the `DAV:response` dedicated to the specific resource.

Let me know if this solved your problem by closing the issue.
Thank you very much for your contribution.
