### ISSUE TITLE
OSX Finder: duplicated entries

### ISSUE THREAD

**Issue by F145h** [OpenMarshal/npm-WebDAV-Server#24]
Strange behavior of OS X Finder is observed as duplicating entries in a file listing. This lasts for a second: folders and files are duplicated, and then they disappear. I have not seen this in any of the WebDAV clients. Windows Explorer also works fine, this issue concerns only the Finder.

![untitled 2](https://user-images.githubusercontent.com/849020/33072167-0ff1cc76-cec7-11e7-9fd6-826f991d7037.png)

**Comment by DavidBeale** [comment]
I'm seeing this as well. Any ideas?

**Comment by AdrienCastex** [comment]
Hello,

I am investigating, but I found no clue why this is happening yet.

**Comment by DavidBeale** [comment]
Thanks for looking into this.

**Comment by enishoca** [comment]
any update on this?

**Comment by zoftc** [comment]
besides the duplicated entries, the size of files are zero and the Finder fails to copy files from webdav to local machine.

**Comment by zoftc** [comment]
I found the duplicated entries and zero size are caused by the "location" of the propfind response.
Please advise whether it can be omitted ?

**Comment by AdrienCastex** [comment]
Hello,

Indeed, the tag `<DAV:location>` is causing trouble in *Finder* of *OS X*. It is (`v2.3.20`) disabled the time to find if the implementation is not correct. In meantime, you can enable it with the server's option `enableLocationTag` if you want to have it in the responses ([more info](https://github.com/OpenMarshal/npm-WebDAV-Server/wiki/Server's-options-and-customizations-%5Bv2%5D)).

Thank you very much for your contribution.
