### ISSUE TITLE
Server error on propfind

### ISSUE THREAD

**Issue by jorfao** [OpenMarshal/npm-WebDAV-Server#25]
Using cadaver, when i list a directory i get the following error on webdav-server:

\webdav-server\lib\manager\v2\fileSystem\FileSystem.js:745
                            pm.getProperties(function (e, bag) {
                               ^

TypeError: pm.getProperties is not a function
    at C:\temp\webdav_server\node_modules\webdav-server\lib\manager\v2\fileSystem\FileSystem.js:745:32
    at C:\temp\webdav_server\node_modules\webdav-server\lib\manager\v2\fileSystem\FileSystem.js:1163:13
    at Workflow.doneFn (C:\temp\webdav_server\node_modules\webdav-server\lib\user\v2\privilege\PrivilegeManager.js:23:50)
    at C:\temp\webdav_server\node_modules\webdav-server\lib\helper\Workflow.js:44:57
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by AdrienCastex** [comment]
Hello,

It is working for me (`v2.3.13`), with the `virtual file system` and with the `physical file system`.

I need you to tell me the procedure to reproduce this error and the mount mapping of your server near the directory you tried to list.

This error is occurring when the `_propertyManager` method of the file system is giving an object which doesn't respect the `IPropertyManager` interface.

```typescript
interface IPropertyManager
{
    setProperty(name : string, value : ResourcePropertyValue, attributes : PropertyAttributes, callback : SimpleCallback) : void
    getProperty(name : string, callback : Return2Callback<ResourcePropertyValue, PropertyAttributes>) : void
    removeProperty(name : string, callback : SimpleCallback) : void
    getProperties(callback : ReturnCallback<PropertyBag>, byCopy ?: boolean) : void
}
```
