### ISSUE TITLE
Is the openWriteStream event called when writing is complete

### ISSUE THREAD

**Issue by yueduz** [OpenMarshal/npm-WebDAV-Server#26]
Is the openWriteStream event called when writing is complete? I need to add a delay, or sometimes can not read the file.

Whether or not the reason for writing is not completed
```js
server.on('openWriteStream',function (ctx, _fs, paths, data){setTimeout(()=>blogSync.openWriteStream(ctx, _fs, paths, data ),1000)} );

```

**Comment by AdrienCastex** [comment]
Hello,

The event `openWriteStream` is triggered when the stream is opened with success.

The stream is not provided as an argument of the event, but I think it may be a good thing. This would help to attach events to the stream.

What is `blogSync` in your case?

**Comment by yueduz** [comment]
I want to call the function when the write is completed, but did not find the corresponding event

**Comment by AdrienCastex** [comment]
When I will add the stream to the event, you will be able to do so :

```javascript
server.on('openWriteStream', function(ctx, fs, paths, data) {
    data.stream.on('finish', function() {
        console.log('Done');
    });
});
```

I'll keep you in touch.

**Comment by yueduz** [comment]
ex.openWriteStream = async function (ctx, _fs, paths, data) {
console.log(data.stream);//undefined
  data.stream.on('finish', function(a,b) {
//Can not be triggered
    console.log(a,b);
    console.log('a,b');
});
}

------
server.on('openWriteStream',ex.openWriteStream  )

**Comment by AdrienCastex** [comment]
Yes, as I said, it is not implemented yet, but it will soon.

**Comment by AdrienCastex** [comment]
You can now (`v2.3.16`) use it.

I let you close the issue if this solved your problem.

Thank you very much for your contribution.

**Comment by yueduz** [comment]
Thank you very much, he is working normally
