### ISSUE TITLE
XML error when getting directory list

### ISSUE THREAD

**Issue by tedeh** [OpenMarshal/npm-WebDAV-Server#27]
Thanks for a great and well documented library.

I'm trying to setup a simple example that looks like this:

```javascript
'use strict';

const webdav = require('webdav-server').v2;

const rootFileSystem = new webdav.PhysicalFileSystem('/scratch');

const server = new webdav.WebDAVServer({
  port: 1900,
  hostname: 'localhost',
  rootFileSystem,
});

server.afterRequest((arg, next) => {
  console.log('>>', arg.request.method, arg.fullUri(), '>', arg.response.statusCode, arg.response.statusMessage);
  next();
});

server.start(httpServer => {
  console.log('Server started: ' + JSON.stringify(httpServer.address()));
});
```

I've been using a tool called [davix](https://github.com/cern-it-sdc-id/davix) to query it. All the operations work fine (put, rm, mkdir, get, etc) except `davix-ls` which gives this error:
```shell
$ davix-ls dav://localhost:1900
(Davix::XMLParser) Error: XML Parsing Error: XML parse error at line 1: undeclared namespace prefix
```

Now this might be a problem with Davix, however validating the XML body given by Davix yields this:

`response.xml`
```xml
<?xml version="1.0" encoding="utf-8"?><D:multistatus xmlns:D="DAV:"><D:response><D:href>http://localhost:1900/</D:href><D:propstat><D:status>HTTP/1.1 200 OK</D:status><D:prop><D:getlastmodified>Thu, 15 Mar 2018 04:50:57 GMT</D:getlastmodified><D:creationdate>2018-03-15T04:50:57-01:00</D:creationdate><D:resourcetype><D:collection/></D:resourcetype><D:displayname></D:displayname></D:prop></D:propstat><D:location><D:href>http://localhost:1900/</D:href></D:location><D:propstat><D:prop><a:getcontentlength xmlns:a="DAV:"/><a:quota-used-bytes xmlns:a="DAV:"/><LCGDM:mode/><a:owner xmlns:a="DAV:"/><a:group xmlns:a="DAV:"/></D:prop><D:status>HTTP/1.1 404 Not Found</D:status></D:propstat></D:response><D:response><D:href>http://localhost:1900/hello.txt</D:href><D:propstat><D:status>HTTP/1.1 200 OK</D:status><D:prop><D:getlastmodified>Thu, 15 Mar 2018 04:49:36 GMT</D:getlastmodified><D:creationdate>2018-03-15T04:49:36-01:00</D:creationdate><D:resourcetype/><D:displayname>hello.txt</D:displayname><D:getcontentlength>14</D:getcontentlength></D:prop></D:propstat><D:location><D:href>http://localhost:1900/hello.txt</D:href></D:location><D:propstat><D:prop><a:quota-used-bytes xmlns:a="DAV:"/><LCGDM:mode/><a:owner xmlns:a="DAV:"/><a:group xmlns:a="DAV:"/></D:prop><D:status>HTTP/1.1 404 Not Found</D:status></D:propstat></D:response></D:multistatus>
```

```shell
$ xmllint -valid response.xml
response.xml:1: validity error : Validation failed: no DTD found !
<?xml version="1.0" encoding="utf-8"?><D:multistatus xmlns:D="DAV:"><D:response>
                                                                   ^
response.xml:1: namespace error : Namespace prefix LCGDM on mode is not defined
getcontentlength xmlns:a="DAV:"/><a:quota-used-bytes xmlns:a="DAV:"/><LCGDM:mode
                                                                               ^
response.xml:1: namespace error : Namespace prefix LCGDM on mode is not defined
</D:location><D:propstat><D:prop><a:quota-used-bytes xmlns:a="DAV:"/><LCGDM:mode
```

Which leads me to believe something might be wrong with the XML output.

I'm new to DAV — thanks for your understanding. Do you have any idea what if anything I'm doing wrong?

**Comment by tedeh** [comment]
FYI it works to open the server example above in Finder with the "Connect to server" utility.

**Comment by AdrienCastex** [comment]
Hello,

Sorry for the late reply.

I believe the problem is from the tag `<LCGDM:mode/>`. It is added in a `PROPFIND` response when required in the request, but the code of the server did not create a valid namespace for this tag. I fixed that on the version `2.3.17`, now it should be working well.

I still need you to test and tell me if this solved your problem.
Thank you very much for your contribution.

**Comment by tedeh** [comment]
I installed `webdav-server@2.3.18` and unfortunately I'm getting the same error: `(Davix::XMLParser) Error: XML Parsing Error: XML parse error at line 1: undeclared namespace prefix`

**Comment by AdrienCastex** [comment]
Hello,

Indeed, I changed the way to write the elements not found in the response and the namespace management was not supported by this method.

The version `2.3.19` should fix this problem. Be sure to have the version `1.0.3` of the package `xml-js-builder`.
Let me know if the problem is still here or gone.

Thank you.

**Comment by tedeh** [comment]
I can confirm that it works correctly in 2.3.19.
