### ISSUE TITLE
Missing documentation `_lockManager` and `_propertyManager`

### ISSUE THREAD

**Issue by fentas** [OpenMarshal/npm-WebDAV-Server#28]
According to `Custom File System [v2]` the following methods are required to implement
- `_lockManager`
- `_propertyManager`

But I could not find any further information.
What is it for? And how to implement it?
Which properties should be added as properties ( `_propertyManager` )?

Thanks a lot.

Edit: I wrote an error, that I having, in `Gitter` regarding `_lockManager`

**Comment by AdrienCastex** [comment]
Hello,

Sorry for the wait.
Here are two new pages to give some information about `_lockManager` and `_propertyManager`:
* [Custom Lock Manager](https://github.com/OpenMarshal/npm-WebDAV-Server/wiki/Custom-Lock-Manager-%5Bv2%5D)
* [Custom Property Manager](https://github.com/OpenMarshal/npm-WebDAV-Server/wiki/Custom-Property-Manager-%5Bv2%5D)

I hope these pages provides the information you need.
Thank you very much for your contribution.
