### ISSUE TITLE
SSL certificate 2 factor authentication

### ISSUE THREAD

**Issue by Jakobud** [OpenMarshal/npm-WebDAV-Server#30]
Is it possible to implement a 2 factor authentication that uses a certificate + passphrase to authenticate with the WebDAV server?

The client side curl commands for this would be described here:

https://www.qed42.com/blog/using-curl-webdav-two-factor-authentication

and

http://drupalsun.com/purushotam-rai/2015/12/16/using-curl-webdav-two-factor-authentication

Is this something that this WebDAV server module can do?

**Comment by AdrienCastex** [comment]
Hello,

This is not supported yet.
But you still can create a [custom authentication system][Authentication system v2] to implement it.

[Authentication system v2]: Authentication-system-%5Bv2%5D

**Comment by Jakobud** [comment]
Could you give me any guidance on how I would possibly go about implementing this?

**Comment by AdrienCastex** [comment]
Hello,

According to what I understood from your links, you just need to use a key/cert encrypted with a passphrase.
Am I right?

If so, you can just use the HTTPS feature of the server:
```javascript
const server = new webdav.WebDAVServer({
    httpAuthentication: /* [...] */,
    privilegeManager: /* [...] */,
    
    port: 443,
    https: {
        cert: fs.readFileSync(/* [...] */),
        key: fs.readFileSync(/* [...] */)
    }
});
```

Keep me informed.

**Comment by Jakobud** [comment]
Okay, where would you specify the passphrase?

**Comment by AdrienCastex** [comment]
It's in your link ([https://www.qed42.com/blog/using-curl-webdav-two-factor-authentication](https://www.qed42.com/blog/using-curl-webdav-two-factor-authentication)), when executing the command `ssh-keygen -p -f cert.key`.

**Comment by Jakobud** [comment]
I mean in the server setup. Like this?

```
...
https: {
        cert: fs.readFileSync(/* [...] */),
        passphrase: "aksdjlakjsdfl"
    }
});
```

**Comment by AdrienCastex** [comment]
I guess so, but I am not sure. I am not an expert in using a passphrase for SSL.

The option `https` of the WebDAV server is directly used in `https` of the standard library, so do not hesitate to use its [documentation](https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener).
