### ISSUE TITLE
limit accessible space for user

### ISSUE THREAD

**Issue by maisen20** [OpenMarshal/npm-WebDAV-Server#31]
Hello, i'm new with webdav and i have some beginner questions.

How can i limit the accessible space for each user? The user may not store more than 200MB for example and also he may not create subfolders.

And another problem is, when i'm connected with macOS and upload some files, all files have the filesize 0 bytes, but they're stored correctly.

TRhank you and best regads
maisen20

**Comment by AdrienCastex** [comment]
Hello,

It needs more tests, but you can do the limiting of the storage size with the option `storageManager` of the server.

```javascript
const server = new webdav.WebDAVServer({
    storageManager: new webdav.PerUserStorageManager(100) // 100 is the limit of bytes storable (including the name/path, the properties and the content)
});
```

So in your, it wouldn't be `100` (100 Bytes) but `209715200` (for 200 MB = 200 * 1024 * 1024).

You can also limit the rights of the users ([more information in the wiki][User management and privileges v2]):
```javascript
// TypeScript
import { v2 as webdav } from 'webdav-server'
// Javascript
const webdav = require('webdav-server').v2;

// User manager (tells who are the users)
const userManager = new webdav.SimpleUserManager();
const user = userManager.addUser('username', 'password', false);

// Privilege manager (tells which users can access which files/folders)
const privilegeManager = new webdav.SimplePathPrivilegeManager();
privilegeManager.setRights(user, '/', [ 'all' ]);

const server = new webdav.WebDAVServer({
    // HTTP Digest authentication with the realm 'Default realm'
    httpAuthentication: new webdav.HTTPDigestAuthentication(userManager, 'Default realm'),
    privilegeManager: privilegeManager
});

server.start(() => console.log('READY'));
```

About the problem with the file size of 0 bytes, does it persists after a refresh of the client window?

[User management and privileges v2]: ../wiki/User-management-and-privileges-%5Bv2%5D

**Comment by maisen20** [comment]
Hello AdrienCastex,

thank you for your answer, i will test it. 

but where could i found detailed informations about the usage of `storageManager` and its `PerUserStorageManager`? i only found [this site](https://github.com/OpenMarshal/npm-WebDAV-Server/wiki/Server%27s-options-and-customizations-%5Bv2%5D) but no more infos about the usage of storageManager.

**Comment by AdrienCastex** [comment]
There was no documentation about this, but I just created a [page for this][Custom Storage Manager v2].

[Custom Storage Manager v2]: Custom-Storage-Manager-%5Bv2%5D

**Comment by maisen20** [comment]
thank you, but your link is broken ("Page not found").

**Comment by AdrienCastex** [comment]
Sorry, I fixed this.

**Comment by maisen20** [comment]
No problem, thank you for your great support!
