### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by maisen20** [OpenMarshal/npm-WebDAV-Server#32]
Hello together

After starting my webdav-server, everything seems to be running.

If i would like to connect from my computer to the webdav-server, i'm getting followed error:

> /webdav-server/lib/server/v2/commands/Propfind.js:11
    var result = date.toISOString().substring(0, '0000-00-00T00:00:00'.length);
   RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at dateISO8601 (/webdav-server/lib/server/v2/commands/Propfind.js:11:23)
    at /webdav-server/lib/server/v2/commands/Propfind.js:147:46
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

After some console outputs, i've seen that the ticks-value in the `dateISO8601`-function (in /webdav-server/lib/server/v2/commands/Propfind.js) is NaN... And the code at line 10 `var date = new Date(ticks);` throws the error, because `new Date(NaN)` is wrong.

So why is the ticks value NaN, how can i fix that? By checking if ticks is NaN and return an empty string  in the `dateISO8601`-function or what's the better way? i'm sure my solution isn't good...

**Comment by maisen20** [comment]
Hello AdrienCastex,

i'm using MacOS 10.13.4 and on webdav server i'm using the PhysicalFileSystem.

**Comment by AdrienCastex** [comment]
Hello,

I couldn't reproduce this bug. So I fixed it (`v2.3.22`) with a default date if the one provided by the FileSystem is not valid.

Tell me if this fixes your problem.
I think I can find more information if you provide me an archive of the files which produces this bug.

Thank you very much for your contribution.
