### ISSUE TITLE
Help needed - invoking WebDav operations in JS via the webdav server API, instead of running http requests

### ISSUE THREAD

**Issue by lafar6502** [OpenMarshal/npm-WebDAV-Server#36]
Hi, i have just started experimenting with webdav-server and i like the effects,  the webdav functions work very nicely. 
My plan, however, is to provide an accompanying web gui for managing the files via web browser - so we end up with both webdav and web access to the same files and folders. In ideal case integrated with same user auth system for both access channels.
And i'm using the webdav-server implementation as the base for the app, so i'm relying on webdav-server JS apis when implementing the web UI functions. Mostly successful in that, but sometimes it just doesn't work as expected, for example when doing move/copy operation.

Below is my copy/move function - _vd is the webdav server object. So my sequence of operations is to 
1. create external context
2. getResource with the source path - this gets me Resource object
3. then i'm calling copy or move on the resource, giving it the destination path

First of all, this doesnt seem to work correctly with my setup - i get an error when trying to move file between two filesystems (because the application doesn't get the path right - it inserts the 'vol1' into the path even if vol1 is just the alias for c:\temp\wd2 folder - because vo1 is the filesystem i have added to webdav).

And my question is - is this a correct approach? Or should i be using the apis in a different way?
Can you provide some examples of how to work with that?
thanks
rg

```javascript  
path: Path { paths: [ 'label2.zpl' ] } }
error { '0':
   { Error: EINVAL: invalid argument, rename 'c:\temp\wd2\label2.zpl' -> 'c:\temp\wd2\vol1\label2.zzzzpl'
     errno: -4071,
     code: 'EINVAL',
     syscall: 'rename',
     path: 'c:\\temp\\wd2\\label2.zpl',
     dest: 'c:\\temp\\wd2\\vol1\\label2.zzzzpl' },
  '1': undefined }
```

```javascript  
function handle_copy(sourcePath, targetPath, isMove, req, res) {
    var ctx = _vd.createExternalContext();
    _vd.getResource(ctx, sourcePath, function(e, rc) {
        console.log('got rc', e, rc);
        if (e) {
            throw new Error();
        }
        var cb = function(e, k) {
            if (e) {
                console.log('error', arguments);
                return err('failed to copy:' + e, res);                  
            } 
            console.log('done', k);
            return returnJson({
                data: {
                    id: sourcePath,
                    type: 'file',
                    attributes: {
                        path: sourcePath,
                        writable: 0,
                        readable: 0
                    }
                }
            }, res);
        }
        if (isMove) {
            rc.move(targetPath, true, cb);
        }
        else {
            rc.copy(targetPath, true, -1, cb);
        }
    });
}
```

**Comment by AdrienCastex** [comment]
Hello,

A resource is just an interface to a file system.
When calling `rc.move(...)`, it will call the method `move` of the file system mounted at the path of the resource.
The method `move` of the file system allows to move a resource inside the file system, not outside.
To do a cross file system move, you can use the standard method `standardMove`.

*Note:* it's the same with the method `copy`.

```javascript
var ctx = _vd.createExternalContext();

_vd.getResource(ctx, sourcePath, function(e, rcSource) {
    _vd.getResource(ctx, targetPath, function(e, rcTarget) {
        if(rcTarget.fs === rcSource.fs)
        { // Keep the special behaviour of the move/copy of the file system
            if(isMove)
                rcSource.move(targetPath, true, cb);
            else
                rcSource.copy(targetPath, true, -1, cb);
        }
        else
        { // Cross file system move/copy
            if(isMove)
                _vd.StandardMethods.standardMove(ctx, rcSource.path, rcSource.fs, rcTarget.path, rcTarget.fs, true, cb);
            else
                _vd.StandardMethods.standardCopy(ctx, rcSource.path, rcSource.fs, rcTarget.path, rcTarget.fs, true, -1, cb);
        }
    });
});
```

Tell me if that answered your question and if it is working as you expected.

**Comment by lafar6502** [comment]
Thanks!

Still, i think there might be some error in the way fs.getRealPath() is implemented

when i ask the app to get me the real path of this resource (file):
`/vol1/boxing_mobile.png`
i get
`'c:\\temp\\wd1\\vol1\\boxing_mobile.png'`


but this is wrong, because of the way vol1 and vol2 filesystems are set up:
`
server.setFileSystem('/vol1', new webdav.PhysicalFileSystem('c:\\temp\\wd1')
server.setFileSystem('/vol2', new webdav.PhysicalFileSystem('c:\\temp\\wd2') ...
`
so, vol1 is an alias for c:\\temp\\wd1 and it should not be included in real path
c:\\temp\\wd1\\**vol1**\\boxing_mobile.png

and that's why the copy / move fails - wrong path on the disk.

**Comment by AdrienCastex** [comment]
No, `getRealPath` is protected and you are not supposed to use it.
It is owned by the class `PhysicalFileSystem` and it is not a standard method of a `FileSystem`.

This method returns an object containing the `resource` instance and the `realPath` which is the `path.join(...)` of the root path you provided to the file system (in your case `c:\\temp\\wd1`) and the path you put in parameter (in your case `/vol1/boxing_mobile.png`), which build the result you obtain.

So, the implementation is right, but you are not supposed to use it. The only case you would be supposed to use it is when you implement a subclass of `PhysicalFileSystem`.

The method you are looking for is `getFullPath`.

```javascript
const ctx = server.createExternalContext();

server.getFileSystem(new webdav.Path('/vol1/boxing_mobile.png'), (fs, rootPath, subPath) => {
    console.log(rootPath.toString(), subPath.toString());

    fs.getFullPath(ctx, subPath, (e, fullPath) => {
        console.log(fullPath.toString());
    })
})
```

**Comment by lafar6502** [comment]
@AdrienCastex i'm not using it directly, trying to use  StandardMethods move or copy function, exactly as in your example. But in such case the application is generating wrong paths (exactly as described) and that's why i did a test with getRealpath. 

here is a test, with move:

`
// JavaScript
const webdav = require('webdav-server').v2;
const path = require('path');

const server = new webdav.WebDAVServer({
    port: 1900
});



server.setFileSystem('vol1', new webdav.PhysicalFileSystem('c:\\temp\\wd1'), (success) => {
    console.log('fs ready');
    server.setFileSystem('vol2', new webdav.PhysicalFileSystem('c:\\temp\\wd2'), (success) => {
        console.log('second fs ready');
        
        
        server.start(function() {
            console.log('server started');
            
            var _vd = server;
            var sourcePath = '/vol1/screen_topbar_workstation.png';
            var targetPath = '/vol1/MOMO';
            var isMove = true;
            
            var ctx = _vd.createExternalContext();
            _vd.getResource(ctx, sourcePath, function(e, rcSource) {
                _vd.getResource(ctx, targetPath, function(e, rcTarget) {
                    
                    var cb = function(e, k) {
                        if (e) {
                            console.log('op error', arguments);
                            return;
                        } 
                        console.log('op success', arguments);
                    }
                    
                    
                    if(rcTarget.fs === rcSource.fs)
                    { // Keep the special behaviour of the move/copy of the file system
                        if(isMove)
                            rcSource.move(targetPath, true, cb);
                        else
                            rcSource.copy(targetPath, true, -1, cb);
                    }
                    else
                    { // Cross file system move/copy
                        if(isMove)
                            _vd.StandardMethods.standardMove(ctx, rcSource.path, rcSource.fs, rcTarget.path, rcTarget.fs, true, cb);
                        else
                            _vd.StandardMethods.standardCopy(ctx, rcSource.path, rcSource.fs, rcTarget.path, rcTarget.fs, true, -1, cb);
                    }
                });
            });
            
            
        });
        
        
    });
    
});
`

error message generated:

`
C:\devs\ufilman>node test.js
fs ready
second fs ready
server started
op error { '0':
   { Error: ENOENT: no such file or directory, rename 'c:\temp\wd1\screen_topbar_workstation.png' -> 'c:\temp\wd1\vol1\MOMO'
     errno: -4058,
     code: 'ENOENT',
     syscall: 'rename',
     path: 'c:\\temp\\wd1\\screen_topbar_workstation.png',
     dest: 'c:\\temp\\wd1\\vol1\\MOMO' },
  '1': undefined }
`

for copy, a different error message:
`
op error { '0': Error: One or more intermediate resources are missing for this operation.
    at Object.<anonymous> (C:\devs\ufilman\node_modules\webdav-server\lib\Errors.js:68:34)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (C:\devs\ufilman\node_modules\webdav-server\lib\resource\v1\std\ResourceChildren.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:654:30),
  '1': undefined }
`

**Comment by AdrienCastex** [comment]
Hello,

My bad, the right parameter in the following part is not `targetPath` (because it is the full path, not the one in the file system), but `rcTarget.path` (because this path is the one in the file system).

```javascript
if(isMove)
    rcSource.move(targetPath, true, cb);
else
    rcSource.copy(targetPath, true, -1, cb);
```

So it must be:

```javascript
if(isMove)
    rcSource.move(rcTarget.path, true, cb);
else
    rcSource.copy(rcTarget.path, true, -1, cb);
```

**Comment by lafar6502** [comment]
Thanks Adrien
one more question to you: users and permissions. Do you think it's possible to use users and permissions model from the webdav server library also for authenticating website (www interface) users? I mean, assuming that i'm using express framework and authenticate an user in the web browser, how to pass this user information further into webdav api so i get access control check? What is the right way to query for user's permissions on a resource? 

R

**Comment by AdrienCastex** [comment]
You can use the HTTP authentication system, or use a custom filter on `ExpressJS`.

Here is a basic example using the authentication in `ExpressJS` with a login page:
```javascript
const app = express();
app.use(cookieParser());

let currentSession = undefined;

app.all('/signin', (req, res) => {
    if(req.query.login === 'ok')
    { // Good credentials, we create, store and send the new session.
        currentSession = Math.random() + 1;
        res.cookie('session', currentSession);
        res.send('You signed in');
    }
    else
    { // Bad credentials, we send an error message.
        res.send('Wrong login');
    }
});

const webdavRoute = '/webdav';
const route = express.Router(webdavRoute);

route.use((req, res, next) => {
    if(!currentSession || !req.cookies || !req.cookies['session'] || req.cookies['session'].toString() !== currentSession.toString())
    { // If the session is not found, stop executing the request and send an error message.
        res.send('You must sign in first');
    }
    else
    { // If session found, go to the next step.
        next();
    }
});
route.use(webdav.extensions.express(webdavRoute, webdavServer));

app.use(route);
app.listen(1900);
```

Of course, you can mix it with a `PrivilegeManager` and a custom authentication instance. [See more in the wiki](https://github.com/OpenMarshal/npm-WebDAV-Server/wiki/User-management-and-privileges-%5Bv2%5D).
