### ISSUE TITLE
Write office document 

### ISSUE THREAD

**Issue by fabianinnova** [OpenMarshal/npm-WebDAV-Server#37]
Hi! I'm trying to use the office uri scheme "ms-word:ofe|u|http://127.0.0.1:1901/test.docx" to open a ms-word file in write mode and save it back to the webdav server, but once I open the file, only have the option to save locally to my pc, I started the server with the first code in the "Quick usage" section from the documentation. You've got some example to reach this?

**Comment by M-jerez** [comment]
Hello, I'm having the same problem!

There are 2 errors, first one if you are not using any authentication, Office is still sending the authentication header tot he server as follows:
```
HTTP >> UNLOCK >> test.docx
authorization: 'Bearer',
```
This can be solved by overriding the default a httpAuthentication of the WebDAV server:
```
const webdav = require("webdav-server").v2;

var HTTPNoAuthentication = (function () {
    function HTTPNoAuthentication(userManager, realm) {
        if (realm === void 0) { realm = 'realm'; }
        this.userManager = userManager;
        this.realm = realm;
    }
    HTTPNoAuthentication.prototype.askForAuthentication = function () {
        return {
            'WWW-Authenticate': 'Basic realm="' + this.realm + '"'
        };
    };
    HTTPNoAuthentication.prototype.getUser = function (ctx, callback) {
        var _this = this;
        _this.userManager.getDefaultUser(function (defaultUser) {
            callback(null, defaultUser);
        });
    };
    return HTTPNoAuthentication;
}());

const server = new webdav.WebDAVServer({
  port: 9090,
  httpAuthentication: new HTTPNoAuthentication(userManager, 'Default realm'),
});

```
Once this is done a new error is produced when saving the error, this is because Ms office is sending an `if` header containing the Lock id as follows:
```
HTTP >> PUT >> test.docx
if: (urn:uuid:3868aac0-5540-1797-00d9-0000c53e9184)
``` 

WebDav server is expecting the `if` header to be as follows: `(<urn:uuid:3868aac0-5540-1797-00d9-0000c53e9184>). see the missing `<>` characters.

This can be solved either by editing the 'If' header before is parsed by WebDAV or editing the WebDAV Source code in the file `webdav-server/lib/helper/v2/IfParser.js` line 38 in the function `parseInternal`.
replacing the regexp:
```
    var rex = /((not)|<([^>]+)>|\[([^\]]+)\]|<(DAV:no-lock)>)/ig;
```
by ne regexp:
```
    var rex = /((not)|<*([^>]+)>*|\[([^\]]+)\]|<(DAV:no-lock)>)/ig
```

This could be easily included in a pull request but not sure if this is compliant whit the WebDav Standard and haven't done any kind of test to check is not breaking existing code.

**Comment by fabianinnova** [comment]
Thnks for the answer, 

> WebDav-BREQUEST >> LOCK >> /test.docx
WebDav-AREQUEST >> LOCK >> 200 OK
WebDav-BREQUEST >> PROPFIND >> /
WebDav-AREQUEST >> PROPFIND >> 207 Multi-Status
WebDav-BREQUEST >> PUT >> /~%24test.docx
WebDav-AREQUEST >> PUT >> 201 Created
WebDav-BREQUEST >> LOCK >> /~%24test.docx
WebDav-AREQUEST >> LOCK >> 200 OK
WebDav-BREQUEST >> HEAD >> /~%24test.docx
WebDav-AREQUEST >> HEAD >> 200 OK
WebDav-BREQUEST >> PUT >> /~%24test.docx
WebDav-AREQUEST >> PUT >> 200 OK
WebDav-BREQUEST >> PROPPATCH >> /~%24test.docx
WebDav-AREQUEST >> PROPPATCH >> 207 Multi-Status
WebDav-BREQUEST >> UNLOCK >> /~%24test.docx
WebDav-AREQUEST >> UNLOCK >> 204 No Content
WebDav-BREQUEST >> PROPFIND >> /~%24test.docx
WebDav-AREQUEST >> PROPFIND >> 207 Multi-Status
WebDav-BREQUEST >> LOCK >> /~%24test.docx
WebDav-AREQUEST >> LOCK >> 200 OK
WebDav-BREQUEST >> GET >> /~%24test.docx
WebDav-AREQUEST >> GET >> 200 OK
WebDav-BREQUEST >> UNLOCK >> /~%24test.docx
WebDav-AREQUEST >> UNLOCK >> 204 No Content
WebDav-BREQUEST >> DELETE >> /~%24test.docx
WebDav-AREQUEST >> DELETE >> 200 OK
WebDav-BREQUEST >> UNLOCK >> /test.docx
WebDav-AREQUEST >> UNLOCK >> 204 No Content
WebDav-BREQUEST >> LOCK >> /test.docx
WebDav-AREQUEST >> LOCK >> 200 OK
WebDav-BREQUEST >> PROPFIND >> /
WebDav-AREQUEST >> PROPFIND >> 207 Multi-Status
WebDav-BREQUEST >> PUT >> /~%24test.docx
WebDav-AREQUEST >> PUT >> 201 Created
WebDav-BREQUEST >> LOCK >> /~%24test.docx
WebDav-AREQUEST >> LOCK >> 200 OK
WebDav-BREQUEST >> HEAD >> /~%24test.docx
WebDav-AREQUEST >> HEAD >> 200 OK
WebDav-BREQUEST >> PUT >> /~%24test.docx
WebDav-AREQUEST >> PUT >> 200 OK
WebDav-BREQUEST >> PROPPATCH >> /~%24test.docx
WebDav-AREQUEST >> PROPPATCH >> 207 Multi-Status
WebDav-BREQUEST >> UNLOCK >> /~%24test.docx
WebDav-AREQUEST >> UNLOCK >> 204 No Content

**Comment by fabianinnova** [comment]
Thanks for the answer, I'm triying the code you posted, but the result is the same, I put some log in the before and after request listeners to understand what is going on and is weird, the request from the windows file explorer are very different than the request from browser using the uri scheme.

When open the document from the browser i never see the "HTTP >> UNLOCK" that you specified.

**From windows file explorer**

> WebDav-BREQUEST >> LOCK >> /test.docx
WebDav-AREQUEST >> LOCK >> 200 OK
WebDav-BREQUEST >> PROPFIND >> /
WebDav-AREQUEST >> PROPFIND >> 207 Multi-Status
WebDav-BREQUEST >> PUT >> /~%24test.docx
WebDav-AREQUEST >> PUT >> 201 Created
WebDav-BREQUEST >> LOCK >> /~%24test.docx
WebDav-AREQUEST >> LOCK >> 200 OK
WebDav-BREQUEST >> HEAD >> /~%24test.docx
WebDav-AREQUEST >> HEAD >> 200 OK
WebDav-BREQUEST >> PUT >> /~%24test.docx
WebDav-AREQUEST >> PUT >> 200 OK
WebDav-BREQUEST >> PROPPATCH >> /~%24test.docx
WebDav-AREQUEST >> PROPPATCH >> 207 Multi-Status
WebDav-BREQUEST >> UNLOCK >> /~%24test.docx
WebDav-AREQUEST >> UNLOCK >> 204 No Content
WebDav-BREQUEST >> PROPFIND >> /~%24test.docx
WebDav-AREQUEST >> PROPFIND >> 207 Multi-Status
WebDav-BREQUEST >> LOCK >> /~%24test.docx
WebDav-AREQUEST >> LOCK >> 200 OK
WebDav-BREQUEST >> GET >> /~%24test.docx
WebDav-AREQUEST >> GET >> 200 OK
WebDav-BREQUEST >> UNLOCK >> /~%24test.docx
WebDav-AREQUEST >> UNLOCK >> 204 No Content
WebDav-BREQUEST >> DELETE >> /~%24test.docx
WebDav-AREQUEST >> DELETE >> 200 OK
WebDav-BREQUEST >> UNLOCK >> /test.docx
WebDav-AREQUEST >> UNLOCK >> 204 No Content
WebDav-BREQUEST >> LOCK >> /test.docx
WebDav-AREQUEST >> LOCK >> 200 OK
WebDav-BREQUEST >> PROPFIND >> /
WebDav-AREQUEST >> PROPFIND >> 207 Multi-Status
WebDav-BREQUEST >> PUT >> /~%24test.docx
WebDav-AREQUEST >> PUT >> 201 Created
WebDav-BREQUEST >> LOCK >> /~%24test.docx
WebDav-AREQUEST >> LOCK >> 200 OK
WebDav-BREQUEST >> HEAD >> /~%24test.docx
WebDav-AREQUEST >> HEAD >> 200 OK
WebDav-BREQUEST >> PUT >> /~%24test.docx
WebDav-AREQUEST >> PUT >> 200 OK
WebDav-BREQUEST >> PROPPATCH >> /~%24test.docx
WebDav-AREQUEST >> PROPPATCH >> 207 Multi-Status
WebDav-BREQUEST >> UNLOCK >> /~%24test.docx
WebDav-AREQUEST >> UNLOCK >> 204 No Content

**From browser using ms-word uri scheme**

> WebDav-BREQUEST >> OPTIONS >> /
WebDav-AREQUEST >> OPTIONS >> 200 OK
WebDav-BREQUEST >> HEAD >> /test.docx
WebDav-AREQUEST >> HEAD >> 200 OK
WebDav-BREQUEST >> GET >> /test.docx
WebDav-AREQUEST >> GET >> 200 OK
WebDav-BREQUEST >> HEAD >> /test.docx
WebDav-AREQUEST >> HEAD >> 200 OK
WebDav-BREQUEST >> GET >> /test.docx
WebDav-AREQUEST >> GET >> 200 OK
WebDav-BREQUEST >> HEAD >> /test.docx
WebDav-AREQUEST >> HEAD >> 200 OK

Any idea?

**Comment by M-jerez** [comment]
@fabianinnova, 

The first Error is on the first LOCK request, I have edited my previous answer to fix it. Apologies about this! So the error was produced when doing MS Office is doing the first LOCK. (As the bearer header is wrong so the server )

The difference between the headers is because the browser is only "opening" the file ("GET" request). The rest of the communication is between MS Office and the WebDAV server, so you can't see those request on the Browser.

I've also added a couple more lines to the code on my previous answer related to the user manager that was not included previously.

Above code solved the problem for me, If you post your code maybe I can help more.

**Comment by fabianinnova** [comment]
@M-jerez 
Thanks again, maybe the logs i send before are missing some information.

This is the code I'm testing.

**app.js**
```javascript
const webdav = require("webdav-server").v2;
const express = require('express');

const app = express();
app.use(express.static('public'));

const userManager = new webdav.SimpleUserManager();
const user = userManager.addUser("TestUser", "Tester01", false);

var HTTPNoAuthentication = (function () {
    function HTTPNoAuthentication(userManager, realm) {
        if (realm === void 0) { realm = 'realm'; }
        this.userManager = userManager;
        this.realm = realm;
    }
    HTTPNoAuthentication.prototype.askForAuthentication = function () {
        return {
            'WWW-Authenticate': 'Basic realm="' + this.realm + '"'
        };
    };
    HTTPNoAuthentication.prototype.getUser = function (ctx, callback) {
        var _this = this;
        _this.userManager.getDefaultUser(function (defaultUser) {
            callback(null, defaultUser);
        });
    };
    return HTTPNoAuthentication;
}());

const server = new webdav.WebDAVServer({
  httpAuthentication: new HTTPNoAuthentication(userManager, 'Default realm'),
});

server.setFileSystem('/', new webdav.PhysicalFileSystem('C:/webdav'), (success) => {
    server.start(() => {
        console.log('READY');
    });
});

server.afterRequest((arg, next) => {
    if(arg.request.method == 'HEAD') {
        console.log('>>', arg.request.method, '>>', arg.response.statusCode, arg.response.statusMessage);
        console.log('>> REQUEST >>');
        console.log(arg.request.headers);
        console.log('>> RESPONSE >>');
        console.log(arg.response.getHeaders());
    }
    next();
});

// Mount the WebDAVServer instance
app.use(webdav.extensions.express('/webdav', server));
app.listen(1901); // Start the Express server
```
**index.html (under public folder)**
```html
<html>
  <head>
    <title>WebDAV test</title>
  </head>
  <body>
    <a href="ms-word:ofe|u|http://127.0.0.1:1901/webdav/test.docx">Abrir</a>
  </body>
</html>
```
Note that I'm mapping a physical file system so in my case is a folder in "C:\webdav\"

**Comment by fabianinnova** [comment]
@M-jerez
Thanks again, maybe the logs i send before are missing some information.

This is the code I'm testing:

**app.js**

```javascript
const webdav = require("webdav-server").v2;
const express = require('express');

const app = express();
app.use(express.static('public'));

const userManager = new webdav.SimpleUserManager();
const user = userManager.addUser("TestUser", "Tester01", false);

var HTTPNoAuthentication = (function () {
    function HTTPNoAuthentication(userManager, realm) {
        if (realm === void 0) { realm = 'realm'; }
        this.userManager = userManager;
        this.realm = realm;
    }
    HTTPNoAuthentication.prototype.askForAuthentication = function () {
        return {
            'WWW-Authenticate': 'Basic realm="' + this.realm + '"'
        };
    };
    HTTPNoAuthentication.prototype.getUser = function (ctx, callback) {
        var _this = this;
        _this.userManager.getDefaultUser(function (defaultUser) {
            callback(null, defaultUser);
        });
    };
    return HTTPNoAuthentication;
}());

const server = new webdav.WebDAVServer({
  httpAuthentication: new HTTPNoAuthentication(userManager, 'Default realm'),
});

server.setFileSystem('/', new webdav.PhysicalFileSystem('C:/webdav'), (success) => {
    server.start(() => {
        console.log('READY');
    });
});

server.afterRequest((arg, next) => {
    if(arg.request.method == 'HEAD') {
        console.log('>>', arg.request.method, '>>', arg.response.statusCode, arg.response.statusMessage);
        console.log('>> REQUEST >>');
        console.log(arg.request.headers);
        console.log('>> RESPONSE >>');
        console.log(arg.response.getHeaders());
    }
    next();
});

// Mount the WebDAVServer instance
app.use(webdav.extensions.express('/webdav', server));
app.listen(1901); // Start the Express server
```

**index.html (under public folder)**

```html
<html>
  <head>
    <title>WebDAV test</title>
  </head>
  <body>
    <a href="ms-word:ofe|u|http://127.0.0.1:1901/webdav/test.docx">Open</a>
  </body>
</html>
```

Note that I'm mapping a physical file system so in my case is a folder in "C:\webdav"

**Comment by M-jerez** [comment]
@fabianinnova 
My implementation is pretty similar but I'm not using express in the same port.
I'm using a different port exclusively for the WebDAV server and settign the access control headers.

```js
function setHeaders(arg) {
  if (arg.request.method === "OPTIONS") {
    arg.response.setHeader(
      "Access-Control-Allow-Methods",
      "PROPPATCH,PROPFIND,OPTIONS,DELETE,UNLOCK,COPY,LOCK,MKCOL,MOVE,HEAD,POST,PUT,GET"
    );
    arg.response.setHeader(
      "allow",
      "PROPPATCH,PROPFIND,OPTIONS,DELETE,UNLOCK,COPY,LOCK,MKCOL,MOVE,HEAD,POST,PUT,GET"
    );
    arg.response.setHeader("Access-Control-Allow-Headers", "*");
    arg.response.setHeader("Access-Control-Allow-Origin", "*");
  }
  arg.response.setHeader("MS-Author-Via", "DAV");
}
```

Be sure your `allow` header includes all the WebDAV Methods `PROPFIND, LOCK, UNLOCK, ...` so Ms Office knows is a WebDAV server.
Also, the responses to the HEAD method should include the `content-length` header.

Other than that can't imagine what might be the cause of your error, maybe something related to express.js.

**Comment by fabianinnova** [comment]
@M-jerez 
I added the setHeaders function to the beforRequest listener and it works! I also included the code of your first answer because ms-word keeps saying "The document is locked for editing by another user", but unfortunately, even though the file is saved correctly, I can not remove the error message.

**Comment by fabianinnova** [comment]
@M-jerez 
The code in your first answer needs to call a next(); after the call of setHeaders() in the beforeRequest() listener, otherwise, the requests will be stuck in that listener. 

```javascript
server.beforeRequest((arg, next) => {
    setHeaders;
    next();
});
```
