### ISSUE TITLE
Working example for serveing a physical folder

### ISSUE THREAD

**Issue by mStirner** [OpenMarshal/npm-WebDAV-Server#39]
I struggle with this simple setup.
```javascript

const webdav = require('./lib/index.js').v2;// JavaScript


const server = new webdav.WebDAVServer({
    port: 1900
});

server.afterRequest((arg, next) => {
    // Display the method, the URI, the returned status code and the returned message
    console.log('>>', arg.request.method, arg.uri, '>', arg.response.statusCode, arg.response.statusMessage);
    // If available, display the body of the response
    console.log(arg.responseBody);
    next();
});

// User manager (tells who are the users)
const userManager = new webdav.SimpleUserManager();
const user = userManager.addUser('username', 'password', false);

// Privilege manager (tells which users can access which files/folders)
//const privilegeManager = new webdav.SimplePathPrivilegeManager();
//privilegeManager.setRights(user, '/', [ 'all' ]);


server.setFileSystem('/images', new webdav.PhysicalFileSystem('C:\images'), (success) => {
	
    server.start(function(){
			console.log("ready");
	});
	
})
```

The server runs and i can mount the server, but cant read or write to the image folder.
And i cant mount under <host>:<port>/images i must mount the root path from the server, and this give me another problem in windows....

Clients are debain/clonezilla, ubuntu, Windows PE 10, Windows 7

EDIT: Attached logfile/client pic

> 
> node index.js
> 
> ready
> >> PROPFIND undefined > 207 Multi-Status
> <?xml version="1.0" encoding="utf-8"?><D:multistatus xmlns:D="DAV:"><D:response><D:href>http://172.16.0.1:1900/</D:href>
> <D:propstat><D:status>HTTP/1.1 200 OK</D:status><D:prop><D:getlastmodified>Wed, 12 Sep 2018 09:24:20 GMT</D:getlastmodif
> ied><D:resourcetype><D:collection/></D:resourcetype><D:getetag>"f5ee35215d4c7680c7174a9a431c3600"</D:getetag></D:prop></
> D:propstat><D:propstat><D:prop><a:getcontentlength xmlns="DAV:" xmlns:a="DAV:"/><a:executable xmlns="http://apache.org/d
> av/props/" xmlns:a="http://apache.org/dav/props:"/></D:prop><D:status>HTTP/1.1 404 Not Found</D:status></D:propstat></D:
> response><D:response><D:href>http://172.16.0.1:1900/images</D:href><D:propstat><D:status>HTTP/1.1 404 Not Found</D:statu
> s></D:propstat></D:response></D:multistatus>
> >> PROPFIND undefined > 207 Multi-Status
> <?xml version="1.0" encoding="utf-8"?><D:multistatus xmlns:D="DAV:"><D:response><D:href>http://172.16.0.1:1900/</D:href>
> <D:propstat><D:status>HTTP/1.1 200 OK</D:status><D:prop><D:getlastmodified>Wed, 12 Sep 2018 09:24:20 GMT</D:getlastmodif
> ied><D:resourcetype><D:collection/></D:resourcetype><D:getetag>"f5ee35215d4c7680c7174a9a431c3600"</D:getetag></D:prop></
> D:propstat><D:propstat><D:prop><a:getcontentlength xmlns="DAV:" xmlns:a="DAV:"/><a:executable xmlns="http://apache.org/d
> av/props/" xmlns:a="http://apache.org/dav/props:"/></D:prop><D:status>HTTP/1.1 404 Not Found</D:status></D:propstat></D:
> response><D:response><D:href>http://172.16.0.1:1900/images</D:href><D:propstat><D:status>HTTP/1.1 404 Not Found</D:statu
> s></D:propstat></D:response></D:multistatus>
> >> GET undefined > 404 Not Found
> undefined
> >> PROPFIND undefined > 207 Multi-Status
> <?xml version="1.0" encoding="utf-8"?><D:multistatus xmlns:D="DAV:"><D:response><D:href>http://172.16.0.1:1900/</D:href>
> <D:propstat><D:status>HTTP/1.1 200 OK</D:status><D:prop><D:getlastmodified>Wed, 12 Sep 2018 09:24:20 GMT</D:getlastmodif
> ied><D:resourcetype><D:collection/></D:resourcetype><D:getetag>"f5ee35215d4c7680c7174a9a431c3600"</D:getetag></D:prop></
> D:propstat><D:propstat><D:prop><a:getcontentlength xmlns="DAV:" xmlns:a="DAV:"/><a:executable xmlns="http://apache.org/d
> av/props/" xmlns:a="http://apache.org/dav/props:"/></D:prop><D:status>HTTP/1.1 404 Not Found</D:status></D:propstat></D:
> response><D:response><D:href>http://172.16.0.1:1900/images</D:href><D:propstat><D:status>HTTP/1.1 404 Not Found</D:statu
> s></D:propstat></D:response></D:multistatus>
> >> PROPFIND undefined > 207 Multi-Status
> <?xml version="1.0" encoding="utf-8"?><D:multistatus xmlns:D="DAV:"><D:response><D:href>http://172.16.0.1:1900/</D:href>
> <D:propstat><D:status>HTTP/1.1 200 OK</D:status><D:prop><D:getlastmodified>Wed, 12 Sep 2018 09:24:20 GMT</D:getlastmodif
> ied><D:resourcetype><D:collection/></D:resourcetype><D:getetag>"f5ee35215d4c7680c7174a9a431c3600"</D:getetag></D:prop></
> D:propstat><D:propstat><D:prop><a:getcontentlength xmlns="DAV:" xmlns:a="DAV:"/><a:executable xmlns="http://apache.org/d
> av/props/" xmlns:a="http://apache.org/dav/props:"/></D:prop><D:status>HTTP/1.1 404 Not Found</D:status></D:propstat></D:
> response><D:response><D:href>http://172.16.0.1:1900/images</D:href><D:propstat><D:status>HTTP/1.1 404 Not Found</D:statu
> s></D:propstat></D:response></D:multistatus>
> >> GET undefined > 404 Not Found
> undefined

![20180912_112525](https://user-images.githubusercontent.com/5003424/45416017-3456b680-b67f-11e8-81a8-54e4357eeaed.jpg)

**Comment by cantoute** [comment]
Took me a wile to figure it out
I knew it would be something simple, but had to go threw all the project fo find it out.

`
const myRoot = new webdav.PhysicalFileSystem('/path/to/myRoot')

const server = new webdav.WebDAVServer({
	rootFileSystem: myRoot,
})
`

**Comment by AdrienCastex** [comment]
Hello,

Your wrote `'C:\images'` instead of `'C:/images'`. You escape the `i`, which is not understood, so the `\` is removed, leading to mount `C:images` instead of `C:/images`.

This change fixes the tests I did on your code.
I hope this helped you.
