### ISSUE TITLE
GET method should return a Content-Type header

### ISSUE THREAD

**Issue by JbIPS** [OpenMarshal/npm-WebDAV-Server#4]
Hi,

I'm playing a bit with your server but I just discovered that it never returns [`Content-Type` headers](https://tools.ietf.org/html/rfc2616#section-14.17). A lot of applications use that to parse or interpret the result so I think it would be a good addition toward 100% compatibility with the specs.

Thank you

**Comment by AdrienCastex** [comment]
Hello,

I fixed that, now (v1.7.3) the methods GET and HEAD return the `Content-Type` and `Content-Length` headers everytime.

Note : at the moment, for the resources implemented in the module, the value of the `Content-Type` header is base on the extension of the file.

Thank you very much for your contribution!

**Comment by JbIPS** [comment]
Thank you, it's work perfectly!

> Note : at the moment, for the resources implemented in the module, the value of the Content-Type header is base on the extension of the file.

I think that's more than enough for most of the use case 😉
