### ISSUE TITLE
Free space gradually decreasing when using PerUserStorageManager

### ISSUE THREAD

**Issue by tedeh** [OpenMarshal/npm-WebDAV-Server#45]
I'm currently running this library on a production server, and noticed that the quota of free space available when using the `PerUserStorageManager` kept decreasing indefinitely and becoming more and more unrelated to the actual size of the files stored on disk.

**How to replicate**

Server (running version `v2.4.1`):

```javascript
'use strict';

const webdav = require('webdav-server').v2;

const rootFileSystem = new webdav.PhysicalFileSystem(__dirname +  '/scratch');
const storageManager = new webdav.PerUserStorageManager(1024);

const server = new webdav.WebDAVServer({
  port: 1900,
  hostname: 'localhost',
  rootFileSystem,
  storageManager,
});

server.start(httpServer => {
  console.log('Server started: ' + JSON.stringify(httpServer.address()));
});
```

**Step 1**

Query for the amount of quota used:

`curl --silent -X PROPFIND http://127.0.0.1:1900/ | xmllint -format - | grep quota`

Result is zero used bytes out of 1024 bytes possible.

**Step 2**

Upload a test file, and then immediately delete it.

```shell
echo "hello world" > test.txt
davix-put ./test.txt http://localhost:1900/test.txt
davix-rm http://localhost:1900/test.txt
```

**Step 3**

Query for the amount of quota used again:

`curl --silent -X PROPFIND http://127.0.0.1:1900/ | xmllint -format - | grep quota`

Result **should be zero** but it is not.

The issue seems related to this line:
https://github.com/OpenMarshal/npm-WebDAV-Server/blob/2c9312ef76871deb2d52db579155661593128327/src/manager/v2/fileSystem/FileSystem.ts#L567

The space reserved here is never freed, which leads to a gradual decrease in available space until program restart, eventually preventing uploads altogether.

**Comment by AdrienCastex** [comment]
Hello,

Sorry for the wait, I've been very busy lately.

According to my tests, the problem is when the user delete the resource. The content size was not freed.

This should be solved in the version `2.4.2`.
Let me know if it works as expected when it will be available on npm.

Thank you very much for your contribution.
