### ISSUE TITLE
Cannot use stream for PUT request

### ISSUE THREAD

**Issue by JbIPS** [OpenMarshal/npm-WebDAV-Server#5]
I'm trying to create a file with the `PUT` verb by [streaming data into my request](https://www.npmjs.com/package/request#streaming).

From what I saw, it differs from putting the data in the body because of a `contentLength` check. Both create file, but in the case of a `contentLength === 0` (i.e. data is streaming) the request is never piped into the resource file.

You have a lot of branches here so I'm not sure where to pipe the stream but I'd guess you can pipe them every time: worst case scenario the stream ends without any data.

**Comment by AdrienCastex** [comment]
You are right, the content is never piped to the file when there is no `Content-Length` header. The server use a default `Content-Length` when none is provided in the request, and its value is `0`, so the server consider that there is no content to write.

And you are right (again) to say that it is possible to pipe everytime the content to the resource and, I believe, it is the best way to implement the `PUT` method.

You can find the fixed version online (v1.7.4).

Thank you again for your contribution.
(I let you close the issue if you feel that it is fixed)

**Comment by JbIPS** [comment]
Thank you for so much efficiency! 😄 Have fun and carry on!
