### ISSUE TITLE
optionally respond with paths

### ISSUE THREAD

**Issue by srguiwiz** [OpenMarshal/npm-WebDAV-Server#51]
When having a server behind a reverse proxy, for example an Nginx, not only are server names different, but also there is complication with `https:` versus `http;`.

To alleviate the problems, as an experiment I have boldly in `RequestContext` method `fullUri` done a simple `return uri` instead of adding that prefix.

Tests then have shown ability to mount in Windows and on Mac, and to perform some basic operations just fine.

To be conservative I suggest:

```
    if (this.server.options.respondWithPaths)
        return uri;
    else
        return (this.prefixUri() + uri).replace(/([^:])\/\//g, '$1/');
```

If server is configured with `respondWithPaths` truthy this should give responses with

```
		<D:href>/directory1/directory1a/example1.html</D:href>
```

instead of

```
		<D:href>http://server/directory1/directory1a/example1.html</D:href>
```

Such not mentioning schema or server would make this easier behind proxies, reverse proxies, etc..

What is not there must not be fixed.

It appears to be permitted by [RFC 4437](https://tools.ietf.org/html/rfc4437).

An important consideration is not to change behavior those already using the library expect.  Therefore, an optional setting.

**Comment by srguiwiz** [comment]
In case you are wondering how these posts fit together:

I have made pull request #52 even though I cannot get past issue #50.

I am still running a patched 2.4.1, because issue #50 prevents me from using 2.4.3 or 2.4.4.

**Comment by srguiwiz** [comment]
Fyi, even if with the Nginx `proxy_pass` one figures to also do the
```
proxy_set_header Host $host;
```
that gives the right host in `href`s in propfind responses, but it doesn't put in an `https:` instead of the `http:`, i.e. the scheme or protocol of the `href`s isn't right in propfind responses.  Even if the code in this library wouldn't hard code `http`, in a common setup Node Express doesn't see `https:`, unless more custom processing is done.  Hence, best to offer the option to respond with paths only, that avoids many worries, as long as the path remains the same through the proxy, or through multiple proxies, an easier requirement to meet.

**Comment by AdrienCastex** [comment]
Hello,

That's a very nice idea.
I would also think about giving a special header to alter the way the server will respond to its request, because, at the end, the client knows better what it needs.

Thank you very much for your contribution.

**Comment by srguiwiz** [comment]
Is in 2.4.5.  Appears to be working well.  Thank you.
