### ISSUE TITLE
Why the `PhysicalFolder` resource can't get files of specify folder?

### ISSUE THREAD

**Issue by webliupeng** [OpenMarshal/npm-WebDAV-Server#6]
`const server = new webdav.WebDAVServer({
    privilegeManager: pm,
    userManager: um,
    isVerbose: true,
    port: 8889
});

server.addResourceTree({
    r: new webdav.PhysicalFolder('./data', null, pm)
}, (e) => {
    if(e) throw e;
    
    server.start(() => console.log('READY'));
});
`

**Comment by AdrienCastex** [comment]
Hello,

It doesn't because it is a link to a physical folder and display only children you added to it.
At the moment, there is no loader to scan the physical folder and create the resource tree, but it is pretty easy to do. I created a [Gist to show you how to load a full folder](https://gist.github.com/AdrienCastex/6a2a83a9d9cc0fa19fca788ee619fd33).

It was [planned](https://github.com/OpenMarshal/npm-WebDAV-Server/projects/1) to add such a loader in the module (as a static method of a physical resource or the `PhysicalFSManager`). Now I did it, it will be added to the next release (v1.8.2 or v1.9.0).

Note : Your code has a problem, you put your `PrivilegeManager` (I guess) in the argument of the `PhysicalFolder` in place of the `FSManager`. Prefer using `null` or `undefined` instead :
```javascript
new webdav.PhysicalFolder('./data', null, null)
```

**Comment by AdrienCastex** [comment]
In the upcoming release, this will be the way to do it :

### JavaScript
```javascript
const webdav = require('webdav-server');

webdav.PhysicalFolder.loadFromPath('./data', (e, folder) => {
    if(e) throw e;

    const server = new webdav.WebDAVServer({
        port: 1900
    });

    server.addResourceTree(folder, (e) => {
        if(e) throw e;

        server.start((s) => {
            console.log('Server started on port ' + s.address().port + '.');
        });
    });
});
```

### TypeScript
```typescript
import { PhysicalFolder, WebDAVServer } from 'webdav-server'

PhysicalFolder.loadFromPath('./data', (e, folder) => {
    if(e) throw e;

    const server = new WebDAVServer({
        port: 1900
    });

    server.addResourceTree(folder, (e) => {
        if(e) throw e;

        server.start((s) => {
            console.log('Server started on port ' + s.address().port + '.');
        });
    });
});
```

Thank you very much for your question.

**Comment by webliupeng** [comment]
@AdrienCastex thanks for your answer . it's works fine right now.

**Comment by AdrienCastex** [comment]
Hello,

You might be interested in the new `PhysicalGateway` class of the version `1.9.2` which will create a real (and lazy) link to a folder, providing its children automatically.

You can take a look at [the wiki page about the Gateways](https://github.com/OpenMarshal/npm-WebDAV-Server/wiki/Gateway).

Note : The serialization of the properties of sub-resources is not implemented yet for the `PhysicalGateway` file manager (`PhysicalGFSManager`).

**Comment by webliupeng** [comment]
looks great. I will try that later.

**Comment by webliupeng** [comment]
by the way.I got a problem. 
the Reproduce steps：
1.Create a file `1.txt` in a folder via `npm-WebDav-Server`.
2.Remove that file in `Finder`
3.Request that folder again.got http response with status code 500. (After restart `npm-WebDav-Server` this problem would be gone )

**Comment by AdrienCastex** [comment]
That's normal, when you create your `PhysicalFile`, it is a link to a file, but when you remove its source (the file linked), the `PhysicalFile` instance is unable to retrieve the information of this source file, leading to a `500 Internal Server Error`.

There is a way to make the `PhysicalResource` to remove itself automatically when its source file/folder is not available anymore. I work on it and I keep you informed.

**Comment by AdrienCastex** [comment]
Here you are (v1.9.4) :

```javascript
const file = new webdav.PhysicalFile(filePath);
file.removeOnUnavailableSource = true; // tell to remove itself if the resource at filePath is not available anymore.
```

By default, the `removeOnUnavailableSource` property is equal to `false`.
