### ISSUE TITLE
[Windows] Cant serve a root directory with Config.Msi folder

### ISSUE THREAD

**Issue by Cerlancism** [OpenMarshal/npm-WebDAV-Server#61]
If a directory contains this folder, usually in a root of a drive in Windows, the client wont see any other files and folders.

**Comment by AdrienCastex** [comment]
Hello,

I reproduced this problem with the `PhysicalFileSystem` connected to the root of the `C:` drive. Some resources are listed but not accessible, creating an unexpected error while executing the PROPFIND procedure.

I fixed the problem on the version `2.5.0`.
Thank you for your contribution.
