### ISSUE TITLE
modifying local disk content

### ISSUE THREAD

**Issue by belaviyo** [OpenMarshal/npm-WebDAV-Server#62]
Hi,

Is it possible to read a local folder and then dynamically change its file content when delivering?
for example lets assume a file has the following content:
```
time is %time%
```

I would like to replace `%time%` every-time a request is made.

**Comment by AdrienCastex** [comment]
Hello,

Yes, it is possible using a custom file system.
Take a look at [the wiki page about it](https://github.com/OpenMarshal/npm-WebDAV-Server/wiki/Custom-File-System-%5Bv2%5D). You can find an [example here](https://github.com/OpenMarshal/npm-WebDAV-Server/tree/master/examples/v2/webResource) of a custom file system.

You will have to use a `PhysicalFileSystem` as parent class of your custom file system class. In the `openReadStream` method, you will have to create a stream which can change on the fly these kind of things.

I hope this helped you.
