### ISSUE TITLE
Error in events documentation.

### ISSUE THREAD

**Issue by fabianinnova** [OpenMarshal/npm-WebDAV-Server#63]
The event list documented here: https://github.com/OpenMarshal/npm-WebDAV-Server/wiki/Server's-options-and-customizations is wrong, the right one is:

Event name | Description | details argument
-- | -- | --
'create' | Triggered when the create method of a resource is called by the server. | None
'delete' | Triggered when the delete method of a resource is called by the server. | None
'copy' | Triggered when a copy occured. | Created resource (IResource)
'move' | Triggered when the moveTo method of a resource is called by the server. | Destination path (FSPath)
'lock-set' | Triggered when the setLock method of a resource is called by the server. | Created lock (Lock)
'lock-refresh' | Triggered when a lock is refreshed. | Refreshed lock (Lock)
'lock-remove' | Triggered when the removeLock method of a resource is called by the server. | Removed lock (Lock)
'property-set' | Triggered when the setProperty method of a resource is called by the server (not triggered by a copy). | XML element of the request (XMLElement)
'property-remove' | Triggered when the removeProperty method of a resource is called by the server. | XML element of the request (XMLElement)
'openWriteSream' | Triggered when the write method of a resource is called by the server. | None
'openReadStream' | Triggered when the read method of a resource is called by the server. | None

**Comment by AdrienCastex** [comment]
Hello,

No, the documentation page you are linking is for version 1, and in this version, the events are the ones documented (cf `src\server\v1\webDAVServer\Events.ts`).

For the version 2, the documentation misses the information about the events. I just added them: [Server's events](https://github.com/OpenMarshal/npm-WebDAV-Server/wiki/Server's-events-%5Bv2%5D).

Thank you for your contribution.
