### ISSUE TITLE
propfind gives wrong paths if respondWithPaths while mounted at subpath

### ISSUE THREAD

**Issue by srguiwiz** [OpenMarshal/npm-WebDAV-Server#67]
If mounted at `/a/b` and file is `/a/b/c/d.html` then if using `propfind` while `respondWithPaths` option is `true` then will get href `/c/d.html` and that is wrong.

The point of `respondWithPaths` is shorter responses and not having to translate through proxies with different hosts.  That said, it still needs to give correct answers any client software can understand.  It is good to provide absolute paths starting with a slash `/`.  Just has to be right.

Should be `/a/b/c/d.html` .

**Comment by AdrienCastex** [comment]
Hello,

Indeed, the root path must be provided in the response paths.

The fix will be available in a few minutes in the version `2.6.2`.
Thank you very much for your contribution.
